- name: Clone dotfiles
  hosts: all
  tasks:
    - name: Clone dotfiles from GitHub
      ansible.builtin.git:
        repo: "git@github.com:pranavrao145/.dotfiles.git"
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
        recursive: yes
        update: yes
        accept_hostkey: yes
        version: master
      tags:
        - dotfiles
        - dotfiles-clone
- name: Pre-create directories to avoid fully symlinked config directories
  hosts: all
  tasks:
    - name: Run config directory creation script
      script: ../scripts/create-config-dirs
      tags:
        - dotfiles
        - dotfiles-prep
- name: Install dotfiles using stow
  hosts: all
  tasks:
    - name: Delete ~/.zshrc if it exists
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
        state: absent
      tags:
        - dotfiles
        - dotfiles-install
        - remove-zshrc
    - name: Run stow installation script
      script: ../scripts/stow-dotfiles
      tags:
        - dotfiles
        - dotfiles-install
