- name: Set up Git credentials
  hosts: all
  tasks:
    - name: Personal git setup (email)
      community.general.git_config:
        name: user.email
        scope: global
        value: 56097527+pranavrao145@users.noreply.github.com
      tags:
        - git-setup
        - git-setup-email
    - name: Personal git setup (name)
      community.general.git_config:
         name: user.name
         scope: global
         value: Pranav Rao
      tags:
        - git-setup
        - git-setup-name
