- name: Install pacman packages
  hosts: all
  tasks:
    - name: Install keyring
      become: yes
      community.general.pacman:
        name: archlinux-keyring
      tags:
        - pacman
        - keyring
        - packages-primary
    - name: Install from packagelist.txt
      ansible.builtin.shell: curl -s https://raw.githubusercontent.com/pranavrao145/.dotfiles/master/package-lists/pkglist.txt | xargs pacman -Syyu --noconfirm --needed
      become: yes
      tags:
        - pacman
        - native-packages
        - packages-primary
- name: Install paru packages
  hosts: all
  tasks:
    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel
      tags:
        - paru
        - paru-setup
        - packages-primary
    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        validate: "visudo -cf %s"
      tags:
        - paru
        - paru-setup
        - packages-primary
    - name: Set default version of rust
      become: yes
      become_user: aur_builder
      ansible.builtin.shell: rustup default stable
      tags:
        - paru
        - paru-setup
        - rust
        - packages-primary
    - name: Install paru
      become: yes
      become_user: aur_builder
      script: ../scripts/install-paru
      tags:
        - paru
        - paru-install
        - packages-primary
    # NOTE: RUN THIS TASK ALONE. Run nc -p 6969 on the new machine to see output for this task. Command is guaranteed to fail.
    - name: Install paru packages
      become: yes
      become_user: aur_builder
      ansible.builtin.shell: paru -Syyu --needed --noconfirm $(curl -s https://raw.githubusercontent.com/pranavrao145/.dotfiles/master/package-lists/foreignpkglist.txt) > /dev/tcp/localhost/6969 2>&1
      tags:
        - paru
        - foreign-packages
        - packages-secondary
    - name: Delete the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        state: absent
        remove: yes
        force: yes
      tags:
        - paru
        - paru-cleanup
        - packages-tertiary
    - name: Remove home directory for user `aur_builder`
      become: yes
      ansible.builtin.file:
        path: /home/aur_builder
        state: absent
      tags:
        - paru
        - paru-cleanup
        - packages-tertiary
    - name: Remove user `aur_builder` from sudoers
      become: yes
      ansible.builtin.file:
        path: /etc/sudoers.d/11-install-aur_builder
        state: absent
      tags:
        - paru
        - paru-cleanup
        - packages-tertiary
- name: Install snap packages
  hosts: all
  tasks:
    - name: Probe module loop
      become: yes
      ansible.builtin.shell: modprobe loop
      tags:
        - snapd
        - snapd-setup
        - modprobe-loop
        - packages-tertiary
    - name: Make sure snap is running (socket)
      become: yes
      ansible.builtin.systemd:
        name: snapd.socket
        state: started
      tags:
        - snapd
        - snapd-setup
        - packages-tertiary
    - name: Make sure snap is running (daemon)
      become: yes
      ansible.builtin.systemd:
        name: snapd
        state: started
      tags:
        - snapd
        - snapd-setup
        - packages-tertiary
    - name: Install Spotify and OBS Studio
      become: yes
      community.general.snap:
        name:
          - spotify
          - obs-studio
      tags:
        - snapd
        - spotify
        - obs
        - packages-tertiary
