- name: Symlink necessary scripts on to PATH
  hosts: all
  tasks:
    - name: Symlink color scheme script to /usr/bin
      become: yes
      ansible.builtin.file:
        src: /home/cypher/Scripts/system/update_color_scheme.sh
        dest: /usr/bin/update-color-scheme
        state: link
      tags:
        - scripts
        - color-scheme
    - name: Symlink lock script to /usr/bin
      become: yes
      ansible.builtin.file:
        src: /home/cypher/.config/i3lock/lock.sh
        dest: /usr/bin/lock
        state: link
      tags:
        - scripts
        - lock
    - name: Symlink restart_spotify script to /usr/bin
      become: yes
      ansible.builtin.file:
        src: /home/cypher/Scripts/spotify/restart_spotify
        dest: /usr/bin/restart_spotify
        state: link
      tags:
        - scripts
        - restart-spotify
    - name: Symlink system info script to /usr/bin
      become: yes
      ansible.builtin.file:
        src: /home/cypher/Scripts/system/sysinfo.sh
        dest: /usr/bin/sysinfo
        state: link
      tags:
        - scripts
        - sysinfo
    - name: Symlink update script to /usr/bin
      become: yes
      ansible.builtin.file:
        src: /home/cypher/Scripts/system/update.sh
        dest: /usr/bin/update
        state: link
      tags:
        - scripts
        - update
    - name: Symlink tmux-cht script to /usr/bin
      become: yes
      ansible.builtin.file:
        src: /home/cypher/Scripts/tmux/tmux-cht.sh
        dest: /usr/bin/tmux-cht
        state: link
      tags:
        - scripts
        - tmux
        - tmux-cht
    - name: Symlink tmux-sessionizer script to /usr/bin
      become: yes
      ansible.builtin.file:
        src: /home/cypher/Scripts/tmux/tmux-sessionizer
        dest: /usr/bin/tmux-sessionizer
        state: link
      tags:
        - scripts
        - tmux
        - tmux-sessionizer
    - name: Symlink tmux-windowizer script to /usr/bin
      become: yes
      ansible.builtin.file:
        src: /home/cypher/Scripts/tmux/tmux-windowizer
        dest: /usr/bin/tmux-windowizer
        state: link
      tags:
        - scripts
        - tmux
        - tmux-windowizer
    - name: Symlink git switch-worktree script to /usr/bin
      become: yes
      ansible.builtin.file:
        src: /home/cypher/Scripts/git/switch-worktree
        dest: /usr/bin/switch-worktree
        state: link
      tags:
        - scripts
        - git-scripts
        - switch-worktree
- name: Clone necessary scripts to PATH
  hosts: all
  tasks:
    - name: Clone umpv to PATH
      become: yes
      ansible.builtin.shell:
        chdir: /usr/bin
        cmd: wget https://raw.githubusercontent.com/mpv-player/mpv/master/TOOLS/umpv && chmod +x umpv
      tags:
        - scripts
        - umpv
    - name: Clone mapwacom to PATH
      become: yes
      ansible.builtin.shell:
        chdir: /usr/bin
        cmd: https://gist.githubusercontent.com/tom-galvin/6c19fe907945d735c045/raw/f16fa41cac87815bdd2f7da6da302fb272c7db70/mapwacom && chmod +x /usr/bin/mapwacom
      tags:
        - x
        - scripts
        - wacom
