# - name: Set up lightdm
#   hosts: all
#   tasks:
#     - name: Install lightdm config
#       become: yes
#       ansible.builtin.shell: "cp -r {{ lookup('env', 'HOME') }}/.dotfiles/lightdm/lightdm/* /etc/lightdm/"
#       tags:
#         - lightdm
#         - lightdm-config
#     - name: Enable lightdm
#       become: yes
#       ansible.builtin.systemd:
#         name: lightdm
#         enabled: yes
#       tags:
#         - x
#         - lightdm
#         - lightdm-config
- name: Set up sddm
  hosts: all
  tasks:
    - name: Make sddm conf directory
      become: yes
      ansible.builtin.file:
        path: /etc/sddm.conf.d
        state: directory
      tags:
        - x
        - sddm
        - sddm-config
    - name: Install sddm config
      become: yes
      ansible.builtin.shell: "cp -r {{ lookup('env', 'HOME') }}/.dotfiles/sddm/* /etc/sddm.conf.d/"
      tags:
        - x
        - sddm
        - sddm-config
    - name: Enable sddm
      become: yes
      ansible.builtin.systemd:
        name: sddm
        enabled: yes
      tags:
        - x
        - sddm
        - sddm-config
- name: Set up touchpad
  hosts: all
  tasks:
    - name: Make xorg conf directory
      become: yes
      ansible.builtin.file:
        path: /etc/X11/xorg.conf.d
        state: directory
      tags:
        - x
        - touchpad
    - name: Copy touchpad configuration file
      become: yes
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/.dotfiles/touchpad/90-touchpad.conf"
        dest: /etc/X11/xorg.conf.d/90-touchpad.conf
      tags:
        - x
        - touchpad
- name: Set up JetBrains fonts
  hosts: all
  tasks:
    - name: Create ~/.local/share/fonts if it doesn't exist
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        state: directory
      tags:
        - x
        - jetbrains-fonts
        - ensure-local-share-fonts
    - name: Download JetBrains Mono Nerd Font
      ansible.builtin.shell:
        chdir: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        cmd: wget -O JetBrainsMono.zip https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip && unzip JetBrainsMono.zip
      tags:
        - x
        - jetbrains-fonts
        - jetbrains-fonts-download
    - name: Clean up original cloned zip files and unnecessary auxilliary files
      ansible.builtin.shell:
        chdir: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        cmd: rm -rf JetBrainsMono.zip readme.md OFL.txt
      tags:
        - x
        - jetbrains-fonts
        - jetbrains-fonts-cleanup
    - name: Refresh font cache
      ansible.builtin.shell:
        chdir: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        cmd: fc-cache -fv
      tags:
        - x
        - jetbrains-fonts
        - jetbrains-fonts-refresh
- name: Set up Hyprland
  hosts: all
  tasks:
    - name: Set up Hyprland auto-login
      become: yes
      ansible.builtin.shell: cp /home/cypher/Scripts/hyprland/skip-username.conf /etc/systemd/system/getty@tty1.service.d/
      tags:
        - hyprland
        - hyprland-autologin
